authorName: default
experimentName: oap-network-morphism
trialConcurrency: 1
maxExecDuration: 2h
maxTrialNum: 200
#choice: local, remote, pai
trainingServicePlatform: local
#searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, NetworkMorphism
  #SMAC (SMAC should be installed through nnictl) 
  builtinTunerName: NetworkMorphism
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
    #for now, this tuner only supports cv domain
    task: common
    #input image width
    #input_width: 32
    #input image channel
    #input_channel: 3
    #number of classes
    n_output_node: 4
trial:
  command: python3 oap_keras.py
  codeDir: .
  gpuNum: 1
